### ISSUE TITLE
Does soundmanager-rails work with Rails 4?

### ISSUE THREAD

**Issue by DavidAllison** [glaszig/soundmanager-rails#10]
In Rails 4, I don't see the SWF files getting copied to the assets subdirectory. Is anyone using this with Rails 4?

**Comment by glaszig** [comment]
yeah. that's due to a change in rails 4. they don't compile loose assets (images) of gems located in `<gem>/vendor/assets/images` anymore: rails/rails#7968

until i get this nailed, please try adding the following to your app (as sugggested in rails/rails#11475):

```
config.assets.precompile << 'swf/soundmanager2.swf'
```

the plan is doing this in the gem automatically but i'm afraid that when you have `config.assets.digest = true` the swf file's name will get a hash appended and cause the soundmanager library to not be able to lazy load the file.  
if this is true, i'll have to patch soundmanager to offer an option to configure the filename as well (unless such option already exists).

**Comment by DavidAllison** [comment]
Very interesting - I see a guy did something similar here:

https://github.com/glaszig/soundmanager-rails/issues/10#issuecomment-26559427

What do you think?

**Comment by glaszig** [comment]
link is broken.

however, the digest issue still daunts me because it's the default and everybody uses it anyway.

**Comment by glaszig** [comment]
alright. you might like to be my guinea pig and checkout master with a humble attempt to get this right:

```
gem 'soundmanager-rails', github: 'glaszig/soundmanager-rails'
```

relevant diff: [link](https://github.com/glaszig/soundmanager-rails/compare/e2e403...e64b873)

**Comment by glaszig** [comment]
Rails 4.0 and proper [asset pipeline support](https://github.com/glaszig/soundmanager-rails/commit/b2aede21e11e57c606d659be89ffad7a10312dd1) arrived in version 1.0. Check it out.
