### ISSUE TITLE
Update Flash files to cross-domain compatible version

### ISSUE THREAD

**Issue by dkubb** [glaszig/soundmanager-rails#4]
I just finished a marathon debugging session on why SM was only working locally, but not on staging or development, and it turns out it was because we serve the asset from a different domain. Locally we use the same domain so it always worked.

It turns out that the SM author distributes cross-domain compatible versions, but we didn't know about it:

https://getsatisfaction.com/schillmania/topics/allowdomain_doesnt_solve_cross_domain_issues

Would you accept a pull request that includes the latest cross domain compatible flash files instead of the domain restricted ones?

**Comment by DavidAllison** [comment]
+1

**Comment by glaszig** [comment]
i guess we're talking about the [swf/soundmanager2_flash_xdomain.zip file](https://github.com/scottschiller/SoundManager2/commits/master/swf/soundmanager2_flash_xdomain.zip)?

i have no objection since it is a common use case for rails applications to get their assets served from other domains.
please extend the readme so that people who might be concerned are made aware of this security issue.

**Comment by glaszig** [comment]
reopening since this is, well, still open ;)

**Comment by DavidAllison** [comment]
@glaszig What do you think about including the suggested files - it seems like they would be good to include by default.

**Comment by glaszig** [comment]
i did not yet test this but please have a look at the branch `feature/crossdomain`.

**Comment by liufengyun** [comment]
@glaszig Thanks for maintaining soundmanager-rails. I've tried the `feature/crossdomain` branch, it doesn't work. I'll fork a repo to debug tomorrow.

**Comment by glaszig** [comment]
thx. if you'll get it sorted out i'd be happy about a pull request.

**Comment by glaszig** [comment]
resolved as of [v0.1.4](https://github.com/glaszig/soundmanager-rails/tree/v0.1.4).
