### ISSUE TITLE
Soundmanager-rails on Heroku with Rackspace CDN

### ISSUE THREAD

**Issue by peteroome** [glaszig/soundmanager-rails#9]
Hi,

I have this gem working locally fine, no problem.

I've deployed my app to Heroku though and Soundmanager doesn't seem to initiate, my audio won't play.

I decided to change my application.js file to require the soundmanager2 lib with debugging so i could work out what the problem was.

``` javascript
#= require soundmanager2
```

When i load this locally, in Chrome's console i'm seeing:

`soundManager: Flash URL required. Call soundManager.setup({url:...}) to get started.`

…this is despite having the soundManager.setup() code in my JS declaring the URL as: window.soundManager.url.

I suspect at this point it's because `window.soundManager.url` actually returns `null`.

On my Heroku app, through the console, i've tried setup through the console, as so:

``` javascript
soundManager.setup({url: 'https://my-rackspace-cdn-url.com/assets/swf/soundmanager2_debug.swf'});
```

However, this doesn't have the desired results and i receive the following error:

`js/flash exception: Error: Error calling method on NPObject.`

Clicking into the offending JS file i see the following error too…

`Soundmanager 2 failed to load (Flash security/load error)`

I'm guessing this might be a crossdomain issue but was wondering if you could offer any advice about using the soundmanager2-rails gem in this sort of setup; app on Heroku, assets on Rackspace.

Thanks

**Comment by glaszig** [comment]
afaik the `application.js` manifest line should be

``` js
//= require soundmanager2
```

because `#` is not valid for introducing comments in javascript.

according to [the docs](http://www.schillmania.com/projects/soundmanager2/doc/#sm-config), the property `url` is expected to have a path as value to which a filename gets appended:

``` js
soundManager.setup({url: 'https://my-rackspace-cdn-url.com/assets/swf/'});
```

also note that, like you apparently already discovered, when you include soundmanager itself (`soundmanager2` instead of `soundmanager`) you won't get [automatic configuration](https://github.com/glaszig/soundmanager-rails/blob/master/lib/assets/javascripts/soundmanager.js.erb) -- that's why you need to configure the `url` property yourself.

you may also be running into crossdomain issues, like you said. the docs about [`usePolicyFile`](http://www.schillmania.com/projects/soundmanager2/doc/) might be helpful?

**Comment by glaszig** [comment]
and make sure you're using at least v0.1.4.

**Comment by glaszig** [comment]
closing this now. if you still have issues just comment below or open a new one.
